// <auto-generated />
using System;
using Group5Flight.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Group5Flight.Migrations
{
    [DbContext(typeof(FlightContext))]
    [Migration("20260404062038_UpdateDeltaImageName")]
    partial class UpdateDeltaImageName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Group5Flight.Models.Airline", b =>
                {
                    b.Property<int>("AirlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AirlineId");

                    b.ToTable("Airlines");

                    b.HasData(
                        new
                        {
                            AirlineId = 1,
                            ImageName = "delta.jpg",
                            Name = "Delta Air Lines"
                        },
                        new
                        {
                            AirlineId = 2,
                            ImageName = "united.png",
                            Name = "United Airlines"
                        },
                        new
                        {
                            AirlineId = 3,
                            ImageName = "american.png",
                            Name = "American Airlines"
                        },
                        new
                        {
                            AirlineId = 4,
                            ImageName = "southwest.png",
                            Name = "Southwest Airlines"
                        });
                });

            modelBuilder.Entity("Group5Flight.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AirlineId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CabinType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Emission")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlightCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FlightId");

                    b.HasIndex("AirlineId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            AircraftType = "Boeing 737-900",
                            AirlineId = 1,
                            ArrivalTime = new DateTime(2000, 1, 1, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            CabinType = "Economy",
                            Date = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2000, 1, 1, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            Emission = 170,
                            FlightCode = "DL900",
                            From = "Chicago",
                            Price = 210m,
                            To = "Dallas"
                        },
                        new
                        {
                            FlightId = 2,
                            AircraftType = "Airbus A321",
                            AirlineId = 2,
                            ArrivalTime = new DateTime(2000, 1, 1, 14, 20, 0, 0, DateTimeKind.Unspecified),
                            CabinType = "Economy Plus",
                            Date = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2000, 1, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Emission = 230,
                            FlightCode = "UA455",
                            From = "Dallas",
                            Price = 295m,
                            To = "Seattle"
                        },
                        new
                        {
                            FlightId = 3,
                            AircraftType = "Boeing 737 MAX 9",
                            AirlineId = 3,
                            ArrivalTime = new DateTime(2000, 1, 1, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            CabinType = "Business",
                            Date = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2000, 1, 1, 6, 45, 0, 0, DateTimeKind.Unspecified),
                            Emission = 140,
                            FlightCode = "AA880",
                            From = "Seattle",
                            Price = 520m,
                            To = "San Francisco"
                        },
                        new
                        {
                            FlightId = 4,
                            AircraftType = "Boeing 737-700",
                            AirlineId = 4,
                            ArrivalTime = new DateTime(2000, 1, 1, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            CabinType = "Basic Economy",
                            Date = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2000, 1, 1, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            Emission = 120,
                            FlightCode = "WN720",
                            From = "San Francisco",
                            Price = 130m,
                            To = "Las Vegas"
                        },
                        new
                        {
                            FlightId = 5,
                            AircraftType = "Airbus A320",
                            AirlineId = 1,
                            ArrivalTime = new DateTime(2000, 1, 1, 13, 10, 0, 0, DateTimeKind.Unspecified),
                            CabinType = "Economy",
                            Date = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2000, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Emission = 200,
                            FlightCode = "DL330",
                            From = "Las Vegas",
                            Price = 240m,
                            To = "Chicago"
                        },
                        new
                        {
                            FlightId = 6,
                            AircraftType = "Boeing 737-800",
                            AirlineId = 2,
                            ArrivalTime = new DateTime(2000, 1, 1, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            CabinType = "Economy Plus",
                            Date = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2000, 1, 1, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Emission = 210,
                            FlightCode = "UA999",
                            From = "Chicago",
                            Price = 275m,
                            To = "Miami"
                        });
                });

            modelBuilder.Entity("Group5Flight.Models.Flight", b =>
                {
                    b.HasOne("Group5Flight.Models.Airline", "Airline")
                        .WithMany("Flights")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("Group5Flight.Models.Airline", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
